const $=s=>document.querySelector(s);
const objectSpeed=$('#objectSpeed'), observerSpeed=$('#observerSpeed');
let playing=false,time=0,last=0,currentFrame='ground';
const fmt=n=>`${n>=0?'+':''}${n}`;
const frameInfo={ground:{label:'地面参照系',help:'眼睛站在地面，两辆车都在移动',bubble:'观察点：地面<br><b>谁在动？</b> 两辆车的位置都在变',readout:'地面看到的小车',eq:'v小车/地 = '},observer:{label:'B车参照系',help:'眼睛坐到B车上，B车变成静止',bubble:'观察点：B车<br><b>谁在动？</b> B车不动，A车相对它移动',readout:'B车看到的A车',eq:'vA/B = '},object:{label:'A车参照系',help:'眼睛坐到A车上，A车变成静止',bubble:'观察点：A车<br><b>谁在动？</b> A车不动，B车相对它移动',readout:'A车看到的B车',eq:'vB/A = '},bird:{label:'飞鸟参照系',help:'眼睛跟着天上的飞鸟，飞鸟变成静止',bubble:'观察点：飞鸟<br><b>谁在动？</b> 两辆车都相对飞鸟移动',readout:'飞鸟看到的小车',eq:'v小车/鸟 = '}};
function update(){const vo=+objectSpeed.value,vr=+observerSpeed.value,vrel=vo-vr;$('#objectSpeedOut').textContent=`${fmt(vo)} m/s`;$('#observerSpeedOut').textContent=`${fmt(vr)} m/s`;$('#objectBadge').textContent=`${fmt(vo)} m/s`;$('#observerBadge').textContent=`${fmt(vr)} m/s`;const setArrow=(id,v)=>{const a=$(id).querySelector('.velocity-arrow');a.style.width=`${12+Math.abs(v)*4}px`;a.style.transform=`scaleX(${v<0?-1:1})`;a.style.transformOrigin=v<0?'right center':'left center'};setArrow('#objectCar',vo);setArrow('#observerCar',vr);setArrow('#bird',3);const birdSpeed=3;const shown=currentFrame==='ground'?vo:currentFrame==='observer'?vrel:currentFrame==='object'?0:vo-birdSpeed;$('#groundReadout').textContent=`${fmt(shown.toFixed(1))} m/s`;$('#relativeReadout').textContent=`${fmt((currentFrame==='object'?vr-vo:currentFrame==='bird'?vr-3:vrel).toFixed(1))} m/s`;$('#primaryReadoutLabel').textContent=frameInfo[currentFrame].readout;$('#eqGround').textContent=vo;$('#eqObserver').textContent=vr;$('#eqObject').textContent=fmt(vo);$('#eqFrame').textContent=`(${fmt(vr)})`;$('#eqRelative').textContent=`${fmt(vrel)} m/s`;$('#trackLabel').textContent=`${frameInfo[currentFrame].label} · x（米）`;$('#frameHelp').textContent=frameInfo[currentFrame].help;$('#conceptBubble').innerHTML=frameInfo[currentFrame].bubble;$('#stageEquation').textContent=`${frameInfo[currentFrame].eq}${fmt(shown)} m/s`;positionCars();}
function positionCars(){const vo=+objectSpeed.value,vr=+observerSpeed.value,birdSpeed=3,speedScale=.45;let ob,or,bi;if(currentFrame==='ground'){ob=27+vo*time*speedScale;or=53+vr*time*speedScale;bi=42+birdSpeed*time*speedScale}else if(currentFrame==='observer'){ob=53+(27-53)+(vo-vr)*time*speedScale;or=53;bi=53+(42-53)+(birdSpeed-vr)*time*speedScale}else if(currentFrame==='object'){ob=27;or=27+(53-27)+(vr-vo)*time*speedScale;bi=27+(42-27)+(birdSpeed-vo)*time*speedScale}else{ob=42+(27-42)+(vo-birdSpeed)*time*speedScale;or=42+(53-42)+(vr-birdSpeed)*time*speedScale;bi=42}ob=Math.max(2,Math.min(91,ob));or=Math.max(2,Math.min(91,or));bi=Math.max(2,Math.min(91,bi));$('#objectCar').style.left=`${ob}%`;$('#observerCar').style.left=`${or}%`;$('#bird').style.left=`${bi}%`;const eye=$('#observerEye');if(currentFrame==='ground'){eye.style.left='50%';eye.style.top='25px'}else if(currentFrame==='observer'){eye.style.left=`${or}%`;eye.style.top='126px'}else if(currentFrame==='object'){eye.style.left=`${ob}%`;eye.style.top='126px'}else{eye.style.left=`${bi}%`;eye.style.top='70px'}}
function animate(ts){if(!playing)return;if(!last)last=ts;time+=(ts-last)/1000;last=ts;$('#timer').textContent=`t = ${time.toFixed(1)} s`;positionCars();requestAnimationFrame(animate)}
[objectSpeed,observerSpeed].forEach(x=>x.addEventListener('input',update));
$('#playBtn').onclick=()=>{playing=!playing;$('#playBtn').textContent=playing?'Ⅱ':'▶';if(playing){last=0;requestAnimationFrame(animate)}};
$('#resetBtn').onclick=()=>{playing=false;time=0;last=0;currentFrame='ground';document.querySelectorAll('.frame-btn').forEach(x=>x.classList.toggle('active',x.dataset.frame==='ground'));$('#playBtn').textContent='▶';$('#timer').textContent='t = 0.0 s';objectSpeed.value=4;observerSpeed.value=2;update()};
$('#demoBtn').onclick=()=>{const a=objectSpeed.value,b=observerSpeed.value;objectSpeed.value=-b;observerSpeed.value=-a;update()};
document.querySelectorAll('.frame-btn').forEach(btn=>btn.onclick=()=>{currentFrame=btn.dataset.frame;document.querySelectorAll('.frame-btn').forEach(x=>x.classList.toggle('active',x===btn));update()});
document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$(`#${btn.dataset.tab}-panel`).classList.add('active')});
const concepts=[['01','运动','物体的位置随时间发生变化，就说它在运动。','点“播放”，看小车位置随时间改变。'],['02','速度','速度表示运动有多快，还要说明方向：速度 = 路程 ÷ 时间。','拖动速度滑块，注意 + 和 − 代表方向。'],['03','参照物','判断运动或静止时，被选来作比较的物体。','点击“我站在：观察车”，观察车就静止了。'],['04','参照系','一整套观察运动的“眼睛”：参照物、方向和计时方法。','同一时刻切换地面、观察车、小车视角。'],['05','坐标系','用原点、方向和刻度给位置标上数字的尺子。','向右为正，向左为负；坐标轴会跟着视角改变。'],['06','相对速度','一个物体相对于另一个物体的速度：v相对 = v甲 − v乙。','在观察车视角，小车速度变成 +4 − (+2) = +2。']];$('#conceptGrid').innerHTML=concepts.map(c=>`<article class="concept-card"><span class="num">${c[0]}</span><h4>${c[1]}</h4><p>${c[2]}</p><div class="example">${c[3]}</div></article>`).join('');
function solve(){const md=+$('#meetDistance').value||0,m1=+$('#meetV1').value||0,m2=+$('#meetV2').value||0;$('#meetAnswer').innerHTML=m1+m2?`他们将在 <b>${(md/(m1+m2)).toFixed(1)} 秒</b> 后相遇`:'速度之和要大于 0';const cd=+$('#chaseDistance').value||0,c1=+$('#chaseV1').value||0,c2=+$('#chaseV2').value||0;$('#chaseAnswer').innerHTML=c1>c2?`小车将在 <b>${(cd/(c1-c2)).toFixed(1)} 秒</b> 后追上`:'后面的速度要更快才能追上'}document.querySelectorAll('.mini-solver input').forEach(i=>i.addEventListener('input',solve));update();solve();